#!/usr/bin/env bash
set -euo pipefail

# ============================================================
# BizFlow NH — Interactive Installer
# ============================================================

BOLD="\033[1m"
BLUE="\033[0;34m"
GREEN="\033[0;32m"
YELLOW="\033[1;33m"
RED="\033[0;31m"
NC="\033[0m"

header() { echo -e "\n${BLUE}${BOLD}$1${NC}"; }
info()   { echo -e "${GREEN}[OK]${NC} $1"; }
warn()   { echo -e "${YELLOW}[!]${NC} $1"; }
error()  { echo -e "${RED}[ERROR]${NC} $1"; exit 1; }

ask() {
    local var=$1 prompt=$2 default=$3
    if [ -n "$default" ]; then
        read -rp "$(echo -e "${BOLD}$prompt${NC} [$default]: ")" input
        eval "$var=\"${input:-$default}\""
    else
        while true; do
            read -rp "$(echo -e "${BOLD}$prompt${NC}: ")" input
            [ -n "$input" ] && break
            echo -e "${RED}  This field is required.${NC}"
        done
        eval "$var=\"$input\""
    fi
}

ask_password() {
    local var=$1 prompt=$2 default=$3
    read -rsp "$(echo -e "${BOLD}$prompt${NC} [$default]: ")" input
    echo
    eval "$var=\"${input:-$default}\""
}

# ── Banner ──
echo -e "${BLUE}${BOLD}"
cat << 'BANNER'

  ____  _     _____ _               _   _ _   _
 | __ )(_)___|  ___| | _____      _| \ | | | | |
 |  _ \| |_  / |_  | |/ _ \ \ /\ / /  \| | |_| |
 | |_) | |/ /|  _| | | (_) \ V  V /| |\  |  _  |
 |____/|_/___|_|   |_|\___/ \_/\_/ |_| \_|_| |_|

  KSeF Integration Platform Installer

BANNER
echo -e "${NC}"

# ── Prerequisites ──
header "Checking prerequisites..."
command -v docker >/dev/null 2>&1 || error "Docker is not installed. Please install Docker first: https://docs.docker.com/engine/install/"
docker compose version >/dev/null 2>&1 || error "Docker Compose v2 is not available."

DOCKER_VERSION=$(docker --version | sed -n 's/.*version \([0-9]*\.[0-9]*\.[0-9]*\).*/\1/p')
info "Docker ${DOCKER_VERSION:-unknown}"
info "Docker Compose $(docker compose version --short 2>/dev/null)"

# ── Deployment mode ──
header "Deployment mode"
echo "  1) dev  — direct port access, no SSL, for development/testing"
echo "  2) prod — Nginx Proxy Manager with SSL, domain-based routing"
echo ""
ask MODE "Choose mode (1=dev, 2=prod)" "1"
case "$MODE" in
    1|dev)  MODE="dev" ;;
    2|prod) MODE="prod" ;;
    *) error "Invalid mode" ;;
esac
info "Mode: $MODE"

# ── Monitoring ──
header "Monitoring stack (Grafana + Prometheus + Tempo + Dozzle)"
ask ENABLE_MONITORING "Enable monitoring? (y/n)" "y"
case "$ENABLE_MONITORING" in
    y|Y|yes) ENABLE_MONITORING="true" ;;
    *) ENABLE_MONITORING="false" ;;
esac
info "Monitoring: $ENABLE_MONITORING"

# ── ACR Credentials ──
header "Azure Container Registry credentials"
echo "  These are provided by BizCode with your license."
ask ACR_USERNAME "ACR Username" ""
ask_password ACR_PASSWORD "ACR Password" ""

echo ""
echo -e "  Logging in to ACR..."
echo "$ACR_PASSWORD" | docker login bizcode.azurecr.io -u "$ACR_USERNAME" --password-stdin >/dev/null 2>&1 \
    || error "ACR login failed. Please check your credentials."
info "ACR login successful"

# ── KSeF Environment ──
header "KSeF environment"
echo "  1) test  — KSeF test environment (ksef-test.mf.gov.pl)"
echo "  2) demo  — KSeF demo environment (ksef-demo.mf.gov.pl)"
echo "  3) prod  — KSeF production (ksef.mf.gov.pl)"
echo ""
ask KSEF_ENV "Choose KSeF environment (1/2/3)" "1"
case "$KSEF_ENV" in
    1|test)  KSEF_BASE_URL="https://ksef-test.mf.gov.pl" ;;
    2|demo)  KSEF_BASE_URL="https://ksef-demo.mf.gov.pl" ;;
    3|prod)  KSEF_BASE_URL="https://ksef.mf.gov.pl" ;;
    *) error "Invalid choice" ;;
esac
info "KSeF: $KSEF_BASE_URL"

# ── Frontend URLs ──
header "Frontend URLs (for CORS and links)"
if [ "$MODE" = "prod" ]; then
    ask BASE_DOMAIN "Base domain (e.g. bizflow.klient.pl)" ""
    ask LETSENCRYPT_EMAIL "Email for Let's Encrypt" ""
    DASHBOARD_URL="https://${BASE_DOMAIN}"
    LANDING_URL="https://${BASE_DOMAIN}"
    info "Dashboard will be available at $DASHBOARD_URL"
else
    ask DASHBOARD_URL "Dashboard URL" "http://localhost:4322"
    LANDING_URL="$DASHBOARD_URL"
    BASE_DOMAIN=""
    LETSENCRYPT_EMAIL=""
fi

# ── Generate secrets ──
header "Generating secrets..."
POSTGRES_PASSWORD="bizflownh-pg-$(openssl rand -hex 8)"
RABBITMQ_PASSWORD="bizflownh-rmq-$(openssl rand -hex 8)"
JWT_KEY="$(openssl rand -base64 48)"
OPENBAO_TOKEN="dev-$(openssl rand -hex 12)"
MINIO_ACCESS_KEY="bizflownh-$(openssl rand -hex 6)"
MINIO_SECRET_KEY="$(openssl rand -base64 32)"

info "PostgreSQL password generated"
info "RabbitMQ password generated"
info "JWT key generated"
info "OpenBao token generated"
info "MinIO credentials generated"

# ── Generate .env ──
header "Generating configuration..."

cat > .env << ENVFILE
# Generated by install.sh on $(date -Iseconds)
# BizFlow NH — KSeF Integration Platform

# ── ACR ──
ACR_USERNAME=${ACR_USERNAME}
ACR_PASSWORD=${ACR_PASSWORD}

# ── PostgreSQL ──
POSTGRES_PASSWORD=${POSTGRES_PASSWORD}

# ── RabbitMQ ──
RABBITMQ_USER=bizflownh
RABBITMQ_PASSWORD=${RABBITMQ_PASSWORD}

# ── JWT ──
JWT_KEY=${JWT_KEY}

# ── KSeF ──
KSEF_BASE_URL=${KSEF_BASE_URL}

# ── OpenBao ──
OPENBAO_TOKEN=${OPENBAO_TOKEN}

# ── MinIO (Object Storage) ──
MINIO_ACCESS_KEY=${MINIO_ACCESS_KEY}
MINIO_SECRET_KEY=${MINIO_SECRET_KEY}

# ── Mode ──
MODE=${MODE}
BASE_DOMAIN=${BASE_DOMAIN}
LETSENCRYPT_EMAIL=${LETSENCRYPT_EMAIL}

# ── Frontend ──
DASHBOARD_URL=${DASHBOARD_URL}
LANDING_URL=${LANDING_URL}

# ── Ports ──
API_PORT=5001
DASHBOARD_PORT=4322

# ── Auto-update (seconds, 0=disabled) ──
WATCHTOWER_INTERVAL=300

# ── Monitoring ──
ENABLE_MONITORING=${ENABLE_MONITORING}
GRAFANA_PORT=3001
GRAFANA_URL=${GRAFANA_URL:-http://localhost:3001}
DOZZLE_PORT=3002
ENVFILE

info ".env generated"

# ── Compose command ──
COMPOSE_CMD="docker compose"
if [ "$ENABLE_MONITORING" = "true" ]; then
    COMPOSE_CMD="$COMPOSE_CMD -f docker-compose.yml -f monitoring/docker-compose.monitoring.yml"
else
    COMPOSE_CMD="$COMPOSE_CMD -f docker-compose.yml"
fi
if [ "$MODE" = "prod" ]; then
    COMPOSE_CMD="$COMPOSE_CMD -f docker-compose.prod.yml"
fi

# Save for ctl.sh
echo "$MODE" > .mode

# ── Pull images ──
header "Pulling images..."
$COMPOSE_CMD pull 2>&1 | tail -5
info "Images pulled"

# ── Start ──
header "Starting BizFlow NH..."
if ! $COMPOSE_CMD up -d 2>&1; then
    warn "Some containers may have failed to start. Check: ./ctl.sh status"
fi

# ── Verify ──
header "Verifying services..."
sleep 5
FAILED=0
RUNNING=0
while IFS= read -r line; do
    name=$(echo "$line" | awk '{print $1}')
    state=$(echo "$line" | awk '{print $2}')
    if [ "$state" = "running" ]; then
        info "$name"
        RUNNING=$((RUNNING + 1))
    else
        warn "$name — $state"
        FAILED=$((FAILED + 1))
    fi
done < <($COMPOSE_CMD ps --format '{{.Name}} {{.State}}' 2>/dev/null)

echo ""
if [ "$FAILED" -gt 0 ]; then
    warn "$RUNNING running, $FAILED failed. Check: ./ctl.sh logs <service>"
else
    info "All $RUNNING services running"
fi

# ── Wait for API to be ready ──
header "Waiting for API..."
for i in $(seq 1 30); do
    if curl -sf "http://localhost:${API_PORT:-5001}/health" >/dev/null 2>&1; then
        info "API is ready"
        break
    fi
    sleep 2
done

# ── Summary ──
header "Installation complete!"
echo ""
echo -e "${BOLD}Services:${NC}"
echo -e "  Dashboard:  ${GREEN}${DASHBOARD_URL}${NC}"
echo -e "  API:        ${GREEN}http://localhost:${API_PORT:-5001}${NC}"
if [ "$MODE" = "prod" ]; then
    echo -e "  NPM:        ${GREEN}http://localhost:81${NC}  (admin@example.com / changeme)"
    echo ""
    echo -e "  ${YELLOW}Configure proxy hosts in Nginx Proxy Manager:${NC}"
    echo -e "    ${BASE_DOMAIN}       →  dashboard:4322"
    echo -e "    api.${BASE_DOMAIN}   →  api:8080"
fi
if [ "$ENABLE_MONITORING" = "true" ]; then
    echo -e "  Grafana:    ${GREEN}http://localhost:${GRAFANA_PORT:-3001}${NC}  (admin / admin)"
    echo -e "  Dozzle:     ${GREEN}http://localhost:${DOZZLE_PORT:-3002}${NC}  (admin / admin)"
fi
echo ""
echo -e "${BOLD}Default login:${NC}"
echo -e "  Email:    ${GREEN}admin@bizflownh.dev${NC}"
echo -e "  Password: ${GREEN}Admin123!${NC}"
echo -e "  ${YELLOW}Change the password after first login!${NC}"
echo ""
echo -e "${BOLD}KSeF:${NC} $KSEF_BASE_URL"
echo ""
echo -e "${BOLD}Management:${NC}"
echo "  ./ctl.sh start    — Start all services"
echo "  ./ctl.sh stop     — Stop all services"
echo "  ./ctl.sh status   — Show status"
echo "  ./ctl.sh logs     — View logs"
echo "  ./ctl.sh update   — Pull latest images and restart"
echo "  ./ctl.sh backup   — Backup database"
echo ""
echo -e "${BOLD}Credentials saved in:${NC} .env"
echo -e "${YELLOW}Keep this file safe — it contains all passwords.${NC}"
echo ""
echo -e "${GREEN}${BOLD}BizFlow NH is ready!${NC}"
